# Generated by Django 5.2.11 on 2026-02-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('unidade', models.CharField(choices=[('KG', 'Quilos'), ('L', 'Litros'), ('UN', 'Unidade'), ('CX', 'Caixa')], max_length=10)),
                ('estoque_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('turno', models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino')], max_length=20)),
            ],
        ),
    ]
