# Generated by Django 5.2.11 on 2026-02-13 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_filaespera'),
        ('diary', '0001_initial'),
        ('pedagogical', '0002_zoneamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='pedagogical.disciplina'),
        ),
        migrations.CreateModel(
            name='PlanoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('conteudo', models.TextField()),
                ('metodologia', models.TextField(blank=True, null=True)),
                ('tarefa_casa', models.TextField(blank=True, null=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_aula', to='academic.turma')),
            ],
        ),
    ]
