# Generated by Django 5.2.11 on 2026-02-12 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "cpf",
                    models.CharField(blank=True, max_length=14, null=True, unique=True),
                ),
                ("data_nascimento", models.DateField()),
                ("nome_mae", models.CharField(blank=True, max_length=255, null=True)),
                ("endereco", models.TextField(blank=True, null=True)),
                (
                    "raca_cor",
                    models.CharField(
                        choices=[
                            ("ND", "Não Declarada"),
                            ("BR", "Branca"),
                            ("PR", "Preta"),
                            ("PA", "Parda"),
                            ("AM", "Amarela"),
                            ("IN", "Indígena"),
                        ],
                        default="ND",
                        max_length=2,
                    ),
                ),
                ("deficiencia", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nis", models.CharField(blank=True, max_length=20, null=True)),
                ("transporte_escolar", models.BooleanField(default=False)),
                ("codigo_inep", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "pessoa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aluno_profile",
                        to="people.pessoa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "escolaridade",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "vinculo_empregaticio",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "pessoa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professor_profile",
                        to="people.pessoa",
                    ),
                ),
            ],
        ),
    ]
