# Generated by Django 5.2.11 on 2026-02-12 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("codigo", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Escola",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("inep", models.CharField(blank=True, max_length=20, null=True)),
                ("endereco", models.TextField(blank=True, null=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
            ],
        ),
        migrations.CreateModel(
            name="NivelEnsino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="AnoLetivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.IntegerField()),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("ativo", models.BooleanField(default=True)),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anos_letivos",
                        to="pedagogical.escola",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Etapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                (
                    "ano_letivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapas",
                        to="pedagogical.anoletivo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatrizCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "disciplinas",
                    models.ManyToManyField(
                        related_name="matrizes", to="pedagogical.disciplina"
                    ),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pedagogical.escola",
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pedagogical.nivelensino",
                    ),
                ),
            ],
        ),
    ]
