# Generated by Django 5.2.11 on 2026-02-13 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zoneamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=255, unique=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoneamentos', to='pedagogical.escola')),
            ],
        ),
    ]
