# Generated by Django 5.2.11 on 2026-02-12 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pedagogical", "0001_initial"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("M", "Matutino"),
                            ("V", "Vespertino"),
                            ("N", "Noturno"),
                            ("I", "Integral"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ano_letivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turmas",
                        to="pedagogical.anoletivo",
                    ),
                ),
                (
                    "matriz_curricular",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pedagogical.matrizcurricular",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Matricula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_matricula", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ATIVA", "Ativa"),
                            ("TRANSFERIDO", "Transferido"),
                            ("ABANDONO", "Abandono"),
                            ("CONCLUIDO", "Concluído"),
                        ],
                        default="ATIVA",
                        max_length=20,
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matriculas",
                        to="people.aluno",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matriculas",
                        to="academic.turma",
                    ),
                ),
            ],
            options={
                "unique_together": {("aluno", "turma")},
            },
        ),
    ]
