# Generated by Django 5.2.11 on 2026-02-13 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('pedagogical', '0002_zoneamento'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('ALOCADO', 'Alocado'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO', max_length=20)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fila_espera', to='people.aluno')),
                ('escola_pretendida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedagogical.escola')),
            ],
        ),
    ]
